#!/usr/bin/env ruby

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "depcop"

json_str = if File.pipe?(STDIN)
             STDIN.read
           else
             file_or_json = ARGV.pop
             File.exist?(file_or_json) ? File.read(file_or_json) : file_or_json
           end

unless json_str
  puts "No input"
  exit
end

Depcop::Cli.run(json_str)
